### ISSUE TITLE
Non of the code runs in chapter 11 (Can't set headers after they are sent)

### ISSUE THREAD

**Issue by jgervin** [markbates/Programming-In-CoffeeScript#1]
If you try running any code in chapter 11 you get the same error "Can't set headers after they are sent" 

Express 3.0.0beta7
CoffeeScript version 1.3.3
Node v0.8.2

http.js:644
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:644:11)
    at ServerResponse.res.setHeader (/Users/work/todo/node_modules/express/node_modules/connect/lib/patch.js:62:20)
    at ServerResponse.res.header (/Users/work/todo/node_modules/express/lib/response.js:280:8)
    at ServerResponse.res.json (/Users/work/todo/node_modules/express/lib/response.js:135:8)
    at Create.global.Responder.Responder.complete (/Users/work/todo/src/controllers/responders/responder.js:27:25)
    at Promise.__bind (/Users/work/todo/src/controllers/responders/responder.js:3:63)
    at Promise.addBack (/Users/work/todo/node_modules/mongoose/lib/promise.js:120:8)
    at Promise.EventEmitter.emit (events.js:88:17)
    at Promise.emit (/Users/work/todo/node_modules/mongoose/lib/promise.js:59:38)
    at Promise.complete (/Users/work/todo/node_modules/mongoose/lib/promise.js:70:20)

**Comment by jgervin** [comment]
If I change the create_responder.coffee file to the following the server no longer throws the error, but it creates two of the same objects.  If I set the title attribute of the todo with "unique: true" It prevents the duplicate creation, but then I do get a browser alert with "undefined" as the message. I am thinking the original setHeader error is caused by the duplicate todo being created while the first one has or is returning.

require "#{__dirname}/responder"

class Responder.Create extends Responder

  respond: (@req, @res) =>
    @todo = new Todo(@req.param('todo'))
    #todo.save(@complete)
    @todo.save (err) =>
      if err?
        res.json(err, 500)
      else
        res.json @todo

**Comment by markbates** [comment]
Have you tried using Express v2.5.2, which is what is bundled with the source code here? It could very well be an issue with v3.beta7. I haven't tried that yet.

**Comment by jgervin** [comment]
I will try it out when I get the chance. Thx.

**Comment by sybsteve** [comment]
Is there a project level package.json in github for chapter 10 especially mongoose, express and ejs?  I'm getting the following select error from Mongoose (I'm running the latest of all the modules).  

```
 TypeError: Invalid select() argument. Must be a string or object.
```

when running the sample

app.get '/api/todos', (req, res) ->
  Todo.find {}, [], {sort: [["created_at", -1]]}, (err, @todos) =>
....

I can eliminate the error by changing this to 

  Todo.find {}, {sort: [["created_at", -1]]}, (err, @todos) =>

or

  Todo.find {}, (err, @todos) =>

but this doesn't display records that are in the mongo database (I'm using the default 'test') in the todo collection.  I've tried a number of things including 

  Todo.find {}, ["title"], {sort: [["created_at", -1]]}, (err, @todos) =>

be each throws their own error.

I'm afraid that the module versions might be the problem but don't see any project level package.json which I think would clarify this.  

Thanks for taking a look.

**Comment by sybsteve** [comment]
On Chapter 11, I'm getting the same error as jgervin.  I'm running all the code from github for that chapter along with 

node 0.8.8
cofffee 1.3.3

on OSX 10.7.5

When you enter a record it throws the "Can't set the header..." error and creates 2 records for the todo you just entered in Mongodb.  In addtion, when you restart the app and refresh the home page, while 2 records were created in Mongo, the app now displays 4 of the same records.  And you can delete 2 of the records that show on the page but if you try and select a third record to delete, the app throws the error "TypeError: Object #<Object> has no method 'set' which isn't surprising since what you selected is a phantom record.

**Comment by sybsteve** [comment]
The good news is that adding, deleting and listing using the code in Chapter 12 works beautifully.

**Comment by temaput** [comment]
Hi, Mark! Just finished reading your book in Russian. Thank you for your wonderfull work! You probably want to remove the .js files from the assets/jquery folder in all of your  examples from the chapter 11. They cause the problem with that "Can't set headers after they are sent" error. Since the connect-assets double includes the scripts it results in double requests...
